/*
 * File: app/view/rol/Win027.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.rol.Win027', {
    extend: 'Ext.Panel',
    alias: 'widget.rol.win027',

    requires: [
        'Legalhelp.view.login.Win002ViewModel1',
        'Legalhelp.view.login.Win002ViewController1',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.ComboBox'
    ],

    controller: 'rol.win027',
    viewModel: {
        type: 'rol.win027'
    },
    id: 'Win027',

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0271',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnWin0271',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnWin0271Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0271',
                            html: '<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">Registrarse</h3>'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Roles',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'usu_id',
                            label: 'Código'
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_nombre_usuario',
                            label: 'Nombre',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'combobox',
                            id: 'cmbWin0271',
                            name: 'rol',
                            label: 'Rol',
                            labelAlign: 'bottom',
                            displayField: 'xxx_rol',
                            store: 'rol.rolCmbStore',
                            valueField: 'rol'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnWin0272',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnWin0272Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin027Added'
    }

});