/*
 * File: app/view/preguntas_frecuentes/Win005.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.preguntas_frecuentes.Win005', {
    extend: 'Ext.Panel',
    alias: 'widget.preguntas_frecuentes.win005',

    requires: [
        'Legalhelp.view.preguntas_frecuentes.Win005ViewModel',
        'Legalhelp.view.preguntas_frecuentes.Win005ViewController',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'preguntas_frecuentes.win005',
    viewModel: {
        type: 'preguntas_frecuentes.win005'
    },
    id: 'Win005',
    layout: 'fit',

    items: [
        {
            xtype: 'list',
            margin: '5 5 5 5',
            itemTpl: [
                '<div><div>{pregunta}:</div><br><div>{respuesta}</div></div>'
            ],
            store: 'preguntas_frecuentes.win005Store'
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0051',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0051Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0052',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0052Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0053',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0053Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0054',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0054Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0051'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin0005Added'
    }

});