/*
 * File: app/view/mensaje/Win029.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.mensaje.Win029', {
    extend: 'Ext.Panel',
    alias: 'widget.mensaje.win029',

    requires: [
        'Legalhelp.view.mensaje.Win029ViewModel',
        'Legalhelp.view.mensaje.Win029ViewController',
        'Ext.field.Text',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.dataview.listswiper.ListSwiper',
        'Ext.dataview.pullrefresh.PullRefresh',
        'Ext.form.Panel',
        'Ext.field.Hidden',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'mensaje.win029',
    viewModel: {
        type: 'mensaje.win029'
    },
    id: 'Win029',
    maxHeight: '100%',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            maxHeight: '100%',
            layout: 'vbox',
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtWin0291',
                    margin: '5 10 5 10',
                    listeners: {
                        change: 'onTxtWin0291Change'
                    }
                },
                {
                    xtype: 'list',
                    id: 'lstWin0291',
                    width: '100%',
                    margin: '10 10 10 10',
                    itemTpl: [
                        '<table width="100%">',
                        '    <tr width="100%">',
                        '        <td width="30%"><div class="user-photo"><img src="{xxx_imagen}" width="30px"/></div></td>',
                        '        <td width="70%"><div class="user-div">{xxx_nombre_usuario}</div></td>',
                        '    </tr>',
                        '</table>'
                    ],
                    store: 'mensaje.win029Store',
                    plugins: [
                        {
                            right: [
                                {
                                    iconCls: 'x-fa fa-arrows',
                                    iconAlign: 'left',
                                    text: 'Direccionar',
                                    commit: 'direcciona',
                                    ui: 'alt confirm'
                                }
                            ],
                            left: [
                                {
                                    iconCls: 'x-fa fa-money',
                                    text: 'Pago',
                                    commit: 'habilitaPago'
                                }
                            ],
                            widget: {
                                xtype: 'listswiperstepper'
                            },
                            type: 'listswiper'
                        },
                        {
                            type: 'pullrefresh'
                        }
                    ],
                    listeners: {
                        childtap: 'onLstWin0291Childtap'
                    }
                },
                {
                    xtype: 'formpanel',
                    id: 'frmWin0291',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            id: 'hdnWin0291',
                            name: 'xxx_ubicacion'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0294',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0294Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0291',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0291Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0292',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0292Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0293',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0293Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0291'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin029Added'
    }

});