/*
 * File: app/view/mensaje/Win007ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.mensaje.Win007ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mensaje.win007',

    onBtnWin0075Tap: function(button, e, eOpts) {
        var idCaso = Ext.getCmp('hdnWin0071').getValue();
        var ubicacion = Ext.getCmp('hdnWin0072').getValue();
        var cliente = Ext.getCmp('hdnWin0073').getValue();

        if(ROL === 'ABG')
        var tipoUsuario = 'abogado';
        else if(ROL === 'CLI')
        var tipoUsuario = 'cliente';
        var mensaje = Ext.getCmp('txtWin0071').getValue();
        Ext.Ajax.request
        ({
            url: '../servidor_legalhelp/mensaje/sendmensaje',
            method: 'POST',
            params:
            {
                caso: idCaso,
                tipo: tipoUsuario,
                ubicacion: ubicacion,
                mensaje: mensaje,
                cliente: cliente
            },
            callback: function(opt, success, response)
            {
                if(success)
                {
                    var data = Ext.JSON.decode(response.responseText);
                    var forma = Ext.getCmp('frmWin0071');
                    forma.submit({
                        url: "../servidor_legalhelp/mensaje/getmensajes",
                        params: {caso:idCaso, tipo_usuario: tipoUsuario, ubicacion: ubicacion},
                        success: function(form, action) {
                            var html = action.data;
                            Ext.getCmp('pnlWin0071').setHtml(html);
                            Ext.getCmp('txtWin0071').setValue('');
                            var panel = Ext.getCmp('pnlWin0071');
                            var d = panel.bodyElement.dom;
                            d.scrollTop = d.scrollHeight - d.offsetHeight;
                        },
                        failure: function(form, action)
                        {
                            Ext.Msg.alert('Error', 'Error de conexión');
                        }
                    });
                    //data.usuario;

                }
                else
                Ext.Msg.alert('Error', 'Error de conexión');
            }
        });
    },

    onBtnWin0071Tap: function(button, e, eOpts) {
        var ubicacion = Ext.getCmp('hdnWin0072').getValue();
        var ventana = '';
        if(ROL === 'ABG')
        ventana = 'mensaje.Win029';
        else if(ROL === 'CLI')
        ventana = 'menu.Win006';
        var panel = Ext.getCmp('pnlWin0071');
        panel.destroy();
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.'+ventana);
    },

    onBtnWin0072Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0073Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0074Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin007Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0071').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
        var panel = Ext.getCmp('pnlWin0071');
        var d = panel.bodyElement.dom;
        d.scrollTop = d.scrollHeight;
        /*var d = myPanel.body.dom;
        d.scrollTop = d.scrollHeight - d.offsetHeight;*/
    }

});