/*
 * File: app/view/mensaje/Win029ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.mensaje.Win029ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mensaje.win029',

    direcciona: function() {
        var lista = Ext.getCmp('lstWin0291');
        var store = lista.getStore();
        var selection = lista._plugins[0].items[0]._record;
        var caso = selection.data.cas_id;
        var rec = Ext.create('model.caso.casomodel');
        var me = this;
        Ext.Ajax.request
        ({
            url: '../servidor_legalhelp/caso/readcaso',
            method: 'POST',
            params:
            {
                id: caso
            },
            success: function (response) {
                var responseData = Ext.JSON.decode(response.responseText);
                if (!responseData.success)
                    Ext.Msg.alert('Error', 'Ha ocurrido un error.');
                else
                {
                    var data = responseData.data;
                    rec.set(data);
                    if (data !== null)
                        Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.caso.Win042', 'frmWin0421', rec);
                    else
                        Ext.Msg.alert('Error', 'Ha ocurrido un error.');
                }
            }
        });
    },

    habilitaPago: function() {
        var lista = Ext.getCmp('lstWin0291');
        var store = lista.getStore();
        var selection = lista._plugins[0].items[0]._record;
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.pago.Win041', 'frmWin0411', selection);
    },

    onTxtWin0291Change: function(field, newValue, oldValue, eOpts) {
        var store = Ext.getCmp('lstWin0291').getStore();
        store.proxy.extraParams = {'filtro': newValue};
        store.load();
    },

    onLstWin0291Childtap: function(list, location, eOpts) {
        var ubicacion = Ext.getCmp('hdnWin0291').getValue();
        var idCaso = location.record.data.cas_id;
        var cliente = location.record.data.cli_id;
        if(ROL === 'ABG')
        var tipoUsuario = 'abogado';
        else if(ROL === 'CLI')
        var tipoUsuario = 'cliente';
        var forma = Ext.getCmp('frmWin0291');
        forma.submit({
            url: "../servidor_legalhelp/mensaje/getmensajes",
            params: {caso:idCaso, tipo_usuario: tipoUsuario, ubicacion: ubicacion},
            success: function(form, action) {
                var html = action.data;
                Ext.getCmp('pnlWin0071').setHtml(html);
                var panel = Ext.getCmp('pnlWin0071');
                var d = panel.bodyElement.dom;
                d.scrollTop = d.scrollHeight;// - d.offsetHeight;
            },
            failure: function(form, action)
            {
                Ext.Msg.alert('Error', 'Error de conexión');
            }
        });

        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.mensaje.Win007', 'frmWin0071', '', [idCaso, cliente, ubicacion], ['hdnWin0071', 'hdnWin0073', 'hdnWin0072']);
    },

    onBtnWin0294Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win028');
    },

    onBtnWin0291Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0292Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0293Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin029Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0291').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
        //Ext.getCmp('lstWin0291').setHtml('<div class="list-chat"><div class="user-photo"></div><div class="user-div">{xxx_nombre_usuario}</div></div>');
    }

});