/*
 * File: app/view/mensaje/Win007.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.mensaje.Win007', {
    extend: 'Ext.Panel',
    alias: 'widget.mensaje.win007',

    requires: [
        'Legalhelp.view.mensaje.Win007ViewModel',
        'Legalhelp.view.mensaje.Win007ViewController',
        'Ext.form.Panel',
        'Ext.field.TextArea',
        'Ext.Button',
        'Ext.field.Hidden',
        'Ext.Toolbar',
        'Ext.menu.Menu'
    ],

    controller: 'mensaje.win007',
    viewModel: {
        type: 'mensaje.win007'
    },
    id: 'Win007',
    width: '100%',
    layout: 'vbox',

    items: [
        {
            xtype: 'panel',
            flex: 12,
            id: 'pnlWin0073',
            width: '100%',
            items: [
                {
                    xtype: 'panel',
                    height: '100%',
                    id: 'pnlWin0071',
                    width: '100%',
                    layout: 'fit'
                }
            ]
        },
        {
            xtype: 'formpanel',
            flex: 1,
            id: 'frmWin0071',
            items: [
                {
                    xtype: 'panel',
                    id: 'pnlWin0072',
                    margin: '0 5 0 5',
                    scrollable: false,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textareafield',
                            flex: 1,
                            height: 30,
                            id: 'txtWin0071',
                            margin: '0 3 0 0',
                            scrollable: 'vertical'
                        },
                        {
                            xtype: 'button',
                            id: 'btnWin0075',
                            iconCls: 'x-fa fa-send',
                            listeners: {
                                tap: 'onBtnWin0075Tap'
                            }
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWin0071',
                    name: 'xxx_caso'
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWin0072',
                    name: 'xxx_ubicacion'
                },
                {
                    xtype: 'hiddenfield',
                    id: 'hdnWin0073',
                    name: 'xxx_cli_id'
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0071',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0071Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0072',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0072Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0073',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0073Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0074',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0074Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0071'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin007Added'
    }

});