/*
 * File: app/view/login/Win002ViewController6.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.login.Win002ViewController6', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.preguntas_frecuentes.win025',

    onBtnWin0251Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.preguntas_frecuentes.Win017');
    },

    onBtnWin0252Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.saveRecord('preguntas_frecuentes.win017Store', 'frmWin0251');
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.preguntas_frecuentes.Win017');
    },

    onWin025Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0251').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    }

});