/*
 * File: app/view/login/WinLogin.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.login.WinLogin', {
    extend: 'Ext.Panel',
    alias: 'widget.login.winlogin',

    requires: [
        'Legalhelp.view.login.WinLoginViewModel',
        'Legalhelp.view.login.WinLoginViewController',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button',
        'Ext.SegmentedButton'
    ],

    controller: 'login.winlogin',
    viewModel: {
        type: 'login.winlogin'
    },
    id: 'WinLogin',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'container',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'formpanel',
                            id: 'frmLogin001',
                            items: [
                                {
                                    xtype: 'image',
                                    height: 150,
                                    id: 'imgWinLogin1',
                                    src: '../servidor_legalhelp/img/logo.png'
                                },
                                {
                                    xtype: 'fieldset',
                                    items: [
                                        {
                                            xtype: 'emailfield',
                                            id: 'txtFrmLogin0011',
                                            label: 'Correo',
                                            labelAlign: 'bottom'
                                        },
                                        {
                                            xtype: 'passwordfield',
                                            id: 'pswFrmLogin0011',
                                            label: 'Contraseña',
                                            labelAlign: 'bottom'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'vbox',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnFrmLogin0011',
                                            ui: '',
                                            margin: '5 5 0 5',
                                            text: 'Iniciar sesión',
                                            listeners: {
                                                tap: 'onBtnFrmLogin0011Tap'
                                            }
                                        },
                                        {
                                            xtype: 'segmentedbutton',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    id: 'btnFrmLogin0012',
                                                    margin: '5 5 0 5',
                                                    text: 'Registrarse',
                                                    listeners: {
                                                        tap: 'onBtnFrmLogin0012Tap'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    id: 'btnFrmLogin0013',
                                                    margin: '5 5 0 5',
                                                    text: 'Olvidé mi contraseña',
                                                    listeners: {
                                                        tap: 'onBtnFrmLogin0013Tap'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});