/*
 * File: app/view/login/WinLoginViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.login.WinLoginViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.login.winlogin',

    onBtnFrmLogin0011Tap: function(button, e, eOpts) {
        var me = this;
        var formulario = Ext.getCmp('frmLogin001');
        var email = Ext.getCmp('txtFrmLogin0011').getValue();
        var password = Ext.getCmp('pswFrmLogin0011').getValue();
        //var win = Ext.getCmp('Win0001');
        //    var win = button.up('panel').up('panel');

        if(email === '' || password === '')
        {
            var msg = 'Llene el usuario y la clave para continuar';
            Ext.Msg.alert('Error',msg);
        }
        else
        {
            //Login sistema
            formulario.submit({
                url    : '../servidor_legalhelp/login',
                scope  : this,
                params: {
                    email:email,
                    password:password
                },
                success: function (response, opts)
                {
                    Ext.Ajax.request
                    ({
                        url: BASE_URL+'/servidor_legalhelp/login/logged',
                        method: 'GET',
                        callback: function(opt, success, response)
                        {
                            if(success)
                            {
                                var data = Ext.JSON.decode(response.responseText);
                                ID_USUARIO = data.usuario;
                                //PIN = data.pin;
                                NOMBRE = data.nomusr;
                                ROL = data.rol;
                                IMAGEN_USUARIO = data.imagen;
                                if(ID_USUARIO)
                                {
                                    if(ROL === 'CLI')
                                    Ext.create('Legalhelp.view.tipo_especialidad.Win001', {fullscreen: true});
                                    else if(ROL === 'ADM')
                                    Ext.create('Legalhelp.view.menu.Win012', {fullscreen: true});
                                    else if(ROL === 'ABG')
                                    Ext.create('Legalhelp.view.menu.Win028', {fullscreen: true});
                                    me.getView().destroy();
                                }
                                else
                                {
                                    //me.getView().destroy();
                                    Ext.create('Legalhelp.view.login.WinLogin', {fullscreen: true});
                                }
                            }
                            else
                            Ext.Msg.alert('Error', 'Error de conexión');
                        }
                    });
                    //Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.tipo_especialidad.Win001');
                },
                failure: function ()
                {
                    var msg = 'Usuario no válido';
                    Ext.Msg.alert('Error',msg);
                }
            });
        }
    },

    onBtnFrmLogin0012Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.usuario.Win002');
    },

    onBtnFrmLogin0013Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.usuario.Win003');
    }

});