/*
 * File: app/view/pago/Win041.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.pago.Win041', {
    extend: 'Ext.Panel',
    alias: 'widget.pago.win041',

    requires: [
        'Legalhelp.view.pago.Win041ViewModel',
        'Legalhelp.view.pago.Win041ViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Hidden',
        'Ext.field.Number',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.menu.Menu'
    ],

    controller: 'pago.win041',
    viewModel: {
        type: 'pago.win041'
    },
    id: 'Win041',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'container',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'formpanel',
                            id: 'frmWin0411',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Ingrese el valor del pago',
                                    items: [
                                        {
                                            xtype: 'hiddenfield',
                                            id: 'hdnWin0411',
                                            name: 'cas_id'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            name: 'valor',
                                            label: 'Valor',
                                            labelAlign: 'bottom',
                                            minValue: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            name: 'xxx_iva',
                                            label: 'Porcentaje IVA',
                                            labelAlign: 'bottom',
                                            maxValue: 100,
                                            minValue: 0
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'button',
                    id: 'btnWin0411',
                    iconCls: 'x-fa fa-money',
                    text: 'Habilita pago',
                    listeners: {
                        tap: 'onBtnWin0411Tap'
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0412',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0412Tap'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnWin0413',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0414',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0414Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0415',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0415Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0416',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0416Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0417',
                                iconCls: 'x-fa fa-arrow-left',
                                listeners: {
                                    tap: 'onBtnWin0417Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0411'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin041Added'
    }

});