/*
 * File: app/view/detalle_pago/Win008.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.detalle_pago.Win008', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.detalle_pago.win008',

    requires: [
        'Legalhelp.view.detalle_pago.Win008ViewModel',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'detalle_pago.win008'
    },
    height: '100%',
    id: 'grdWin0081',
    width: '100%',
    store: 'detalle_pago.win008StoreAux2',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 70,
            dataIndex: 'xxx_detalle',
            text: 'String'
        }
    ]

});