/*
 * File: app/model/especialidad/especialidadModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.model.especialidad.especialidadModel', {
    extend: 'Ext.data.Model',
    alias: 'model.especialidad.especialidadmodel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],


    idProperty: 'esp_id',
    fields: [
        {
            type: 'int',
            name: 'esp_id',
            unique: true
        },
        {
            type: 'int',
            name: 'tes_id'
        },
        {
            type: 'string',
            name: 'nombre'
        },
        {
            type: 'string',
            name: 'descripcion'
        }
    ]

});