/*
 * File: app/view/tipo_tarjeta/Win024.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tipo_tarjeta.Win024', {
    extend: 'Ext.Panel',
    alias: 'widget.tipo_tarjeta.win024',

    requires: [
        'Legalhelp.view.login.Win002ViewModel5',
        'Legalhelp.view.login.Win002ViewController5',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    controller: 'tipo_tarjeta.win024',
    viewModel: {
        type: 'tipo_tarjeta.win024'
    },
    id: 'Win024',

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0241',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnWin0241',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnWin0241Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0241'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Tipo de tarjeta',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'tta_id',
                            label: 'Código',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            name: 'nombre',
                            label: 'Nombre',
                            labelAlign: 'bottom'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnWin0242',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnWin0242Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin024Added'
    }

});