/*
 * File: app/model/mensaje/mensajeModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.model.mensaje.mensajeModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],


    idProperty: 'men_id',
    fields: [
        {
            type: 'int',
            name: 'men_id',
            unique: true
        },
        {
            type: 'int',
            name: 'cas_id'
        },
        {
            type: 'string',
            name: 'mensaje_abogado'
        },
        {
            type: 'string',
            name: 'mensaje_cliente'
        },
        {
            type: 'date',
            name: 'fecha',
            dateFormat: 'Y-m-d H:i:s'
        },
        {
            type: 'string',
            name: 'xxx_nombre_usuario'
        }
    ]

});