/*
 * File: app/view/abogado/Win013.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.abogado.Win013', {
    extend: 'Ext.Panel',
    alias: 'widget.abogado.win013',

    requires: [
        'Legalhelp.view.abogado.Win013ViewModel',
        'Legalhelp.view.abogado.Win013ViewController',
        'Ext.field.Text',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.dataview.listswiper.ListSwiper',
        'Ext.dataview.pullrefresh.PullRefresh',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'abogado.win013',
    viewModel: {
        type: 'abogado.win013'
    },
    id: 'Win013',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'vbox',
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtWin0131',
                    margin: '5 10 5 10',
                    listeners: {
                        change: 'onTxtWin0131Change'
                    }
                },
                {
                    xtype: 'list',
                    id: 'lstWin0131',
                    margin: '10 10 10 10',
                    itemTpl: [
                        '<div>{xxx_nombre_usuario}</div>'
                    ],
                    store: 'abogado.win013Store',
                    plugins: [
                        {
                            right: [
                                {
                                    iconCls: 'x-fa fa-edit',
                                    commit: 'editRecord'
                                }
                            ],
                            widget: {
                                xtype: 'listswiperstepper'
                            },
                            type: 'listswiper'
                        },
                        {
                            type: 'pullrefresh'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0131',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0131Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0132',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0132Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0133',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0133Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0134',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0134Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0131'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin013Added'
    }

});