/*
 * File: app/view/abogado/Win021.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.abogado.Win021', {
    extend: 'Ext.Panel',
    alias: 'widget.abogado.win021',

    requires: [
        'Legalhelp.view.login.Win021ViewModel',
        'Legalhelp.view.login.Win021ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.Img',
        'Ext.field.ComboBox',
        'Ext.field.TextArea'
    ],

    controller: 'abogado.win021',
    viewModel: {
        type: 'abogado.win021'
    },
    id: 'Win021',
    scrollable: true,

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0211',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnWin0211',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnFrmLogin0021Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0211'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Abogado',
                    items: [
                        {
                            xtype: 'image',
                            border: false,
                            height: 100,
                            id: 'imgWin0211',
                            name: 'xxx_archivo'
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'abo_id',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_nombre_usuario',
                            label: 'Nombre',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'combobox',
                            name: 'estado',
                            label: 'Estado',
                            labelAlign: 'bottom',
                            displayField: 'nombre',
                            store: 'abogado.estadoCmbStore',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            name: 'numero_licencia',
                            label: 'N° de licencia',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textareafield',
                            name: 'titulo_profesional',
                            label: 'Título profesional',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'xxx_imagen',
                            label: 'Field'
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'txtWin0211',
                            name: 'xxx_imagen',
                            label: 'Field'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnWin0212',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnWin0212Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin021Added'
    }

});