/*
 * File: app/view/biblioteca/Win036ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.biblioteca.Win036ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.biblioteca.win036',

    editRecord: function() {
        var lista = Ext.getCmp('lstWin0341');
        var store = lista.getStore();
        var selection = lista._plugins[0].items[0]._record;
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.biblioteca.Win035', 'frmWin0351', selection);
    },

    deleteRecord: function() {
        Legalhelp.controller.Funciones.deleteRecord('lstWin0341');
    },

    onBtnWin0341Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.biblioteca.Win034');
    },

    onBtnWin0342Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0343Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0344Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin036Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0361').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    }

});