/*
 * File: app/view/biblioteca/Win035ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.biblioteca.Win035ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.biblioteca.win035',

    onBtnWin0231Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.biblioteca.Win034');
    },

    onBtnWin0232Tap: function(button, e, eOpts) {
        //var id = Ext.getCmp('frmWin0351').getValues().bib_id;
        Legalhelp.controller.Funciones.saveRecord('biblioteca.win034Store', 'frmWin0351');
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.biblioteca.Win034');
    },

    onWin035Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0351').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    }

});