/*
 * File: app/view/biblioteca/Win035.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.biblioteca.Win035', {
    extend: 'Ext.Panel',
    alias: 'widget.biblioteca.win035',

    requires: [
        'Legalhelp.view.biblioteca.Win035ViewModel',
        'Legalhelp.view.biblioteca.Win035ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.TextArea',
        'Ext.field.File'
    ],

    controller: 'biblioteca.win035',
    viewModel: {
        type: 'biblioteca.win035'
    },
    id: 'Win035',

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0351',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnWin0351',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnWin0231Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0351'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Biblioteca',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'bib_id',
                            label: 'Código',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            name: 'nombre',
                            label: 'Nombre',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textareafield',
                            name: 'descripcion',
                            label: 'Descripción',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'filefield',
                            name: 'xxx_archivo',
                            label: 'Imagen',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'txtWin0351',
                            name: 'archivo',
                            label: 'Field'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnWin0352',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnWin0232Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin035Added'
    }

});