/*
 * File: app/view/biblioteca/Win037ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.biblioteca.Win037ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.biblioteca.win037',

    seeRecord: function() {
        var lista = Ext.getCmp('lstWin0371');
        var store = lista.getStore();
        var selection = lista._plugins[0].items[0]._record;
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.biblioteca.Win038');
        var url = '<iframe src="../servidor_legalhelp/img/'+selection.data.archivo+'" width="100%" height="100%"></iframe>';
        Ext.getCmp('pnlWin0382').setHtml(url);
    },

    onTxtWin0371Change: function(field, newValue, oldValue, eOpts) {
        var store = Ext.getCmp('lstWin0371').getStore();
        store.proxy.extraParams = {'filtro': newValue};
        store.load();
    },

    onBtnWin0371Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win028');
    },

    onBtnWin0372Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0373Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0374Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin037Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0371').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
        Ext.getCmp('lstWin0371').getStore().load();
    }

});