/*
 * File: app/view/biblioteca/Win036.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.biblioteca.Win036', {
    extend: 'Ext.Panel',
    alias: 'widget.biblioteca.win036',

    requires: [
        'Legalhelp.view.biblioteca.Win036ViewModel',
        'Legalhelp.view.biblioteca.Win036ViewController',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'biblioteca.win036',
    viewModel: {
        type: 'biblioteca.win036'
    },
    height: '100%',
    id: 'Win036',
    width: '100%',
    layout: 'fit',

    items: [
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0361',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0341Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0362',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0342Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0363',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0343Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0364',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0344Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0361'
                }
            ]
        },
        {
            xtype: 'panel',
            id: 'pnlWin0362',
            layout: 'fit',
            items: [
                {
                    xtype: 'panel',
                    height: '100%',
                    id: 'pnlWin0361',
                    width: '100%',
                    layout: 'fit',
                    bodyStyle: 'background-color:#7e7e7e;background-image: url(../servidor_legalhelp/img/hourglass.gif);background-repeat: no-repeat;'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin036Added'
    }

});