/*
 * File: app/view/tipo_identificacion/Win023.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tipo_identificacion.Win023', {
    extend: 'Ext.Panel',
    alias: 'widget.tipo_identificacion.win023',

    requires: [
        'Legalhelp.view.login.Win023ViewModel',
        'Legalhelp.view.login.Win023ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    controller: 'tipo_identificacion.win023',
    viewModel: {
        type: 'tipo_identificacion.win023'
    },
    id: 'Win023',

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0231',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnWin0231',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnWin0231Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0231',
                            html: '<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">Registrarse</h3>'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Tipo de identificación',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'tid_id',
                            label: 'Código',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            name: 'nombre',
                            label: 'Nombre',
                            labelAlign: 'bottom'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnWin0232',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnWin0232Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin023Added'
    }

});