/*
 * File: app/view/tipo_identificacion/Win014.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tipo_identificacion.Win014', {
    extend: 'Ext.Panel',
    alias: 'widget.tipo_identificacion.win014',

    requires: [
        'Legalhelp.view.tipo_identificacion.Win014ViewModel',
        'Legalhelp.view.tipo_identificacion.Win014ViewController',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.dataview.listswiper.ListSwiper',
        'Ext.dataview.pullrefresh.PullRefresh',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'tipo_identificacion.win014',
    viewModel: {
        type: 'tipo_identificacion.win014'
    },
    id: 'Win014',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'vbox',
            items: [
                {
                    xtype: 'list',
                    id: 'lstWin0141',
                    margin: '10 10 10 10',
                    itemTpl: [
                        '<div>{nombre}</div>'
                    ],
                    store: 'tipo_identificacion.win014Store',
                    plugins: [
                        {
                            right: [
                                {
                                    iconCls: 'x-fa fa-edit',
                                    commit: 'editRecord'
                                }
                            ],
                            left: [
                                {
                                    iconCls: 'x-fa fa-trash',
                                    commit: 'deleteRecord',
                                    ui: 'decline'
                                }
                            ],
                            widget: {
                                xtype: 'listswiperstepper'
                            },
                            type: 'listswiper'
                        },
                        {
                            type: 'pullrefresh'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0141',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0141Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0142',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0142Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0143',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0143Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0144',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0144Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0141'
                },
                {
                    xtype: 'button',
                    id: 'btnWin0145',
                    iconCls: 'x-fa fa-plus',
                    listeners: {
                        tap: 'onBtnWin0145Tap'
                    }
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin014Added'
    }

});