/*
 * File: app/view/tipo_identificacion/Win014ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tipo_identificacion.Win014ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tipo_identificacion.win014',

    deleteRecord: function() {
        Legalhelp.controller.Funciones.deleteRecord('lstWin0141');
    },

    editRecord: function() {
        var lista = Ext.getCmp('lstWin0141');
        var store = lista.getStore();
        var selection = lista._plugins[0].items[0]._record;
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.tipo_identificacion.Win023', 'frmWin0231', selection);
    },

    onBtnWin0141Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win012');
    },

    onBtnWin0142Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0143Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0144Tap: function(button, e, eOpts) {

    },

    onBtnWin0145Tap: function(button, e, eOpts) {
        var rec = Ext.create('model.tipo_identificacion.tipoidentificacionmodel');
        rec.data.tid_id = '0';
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.tipo_identificacion.Win023', 'frmWin0231', rec);
    },

    onWin014Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0141').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
        Ext.getCmp('lstWin0141').getStore().load();
    }

});