/*
 * File: app/model/caso/casoModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.model.caso.casoModel', {
    extend: 'Ext.data.Model',
    alias: 'model.caso.casomodel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],


    idProperty: 'cas_id',
    fields: [
        {
            type: 'int',
            name: 'cas_id',
            unique: true
        },
        {
            type: 'int',
            name: 'abo_id'
        },
        {
            type: 'int',
            name: 'cli_id'
        },
        {
            type: 'int',
            name: 'esp_id'
        },
        {
            type: 'string',
            name: 'nombre'
        },
        {
            type: 'string',
            name: 'descripcion'
        },
        {
            type: 'string',
            name: 'numero_caso'
        },
        {
            type: 'date',
            name: 'fecha_inicio'
        },
        {
            type: 'date',
            name: 'fecha_cierre'
        },
        {
            type: 'float',
            name: 'valor'
        },
        {
            type: 'string',
            name: 'estado',
            unique: true
        }
    ]

});