/*
 * File: app/model/pago/pagoModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.model.pago.pagoModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Number'
    ],


    idProperty: 'pag_id',
    fields: [
        {
            type: 'int',
            name: 'pag_id',
            unique: true
        },
        {
            type: 'int',
            name: 'cas_id'
        },
        {
            type: 'float',
            name: 'total_servicio'
        },
        {
            type: 'float',
            name: 'honorario'
        },
        {
            type: 'float',
            name: 'iva'
        }
    ]

});