/*
 * File: app/view/usuario/Win032.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.usuario.Win032', {
    extend: 'Ext.Panel',
    alias: 'widget.usuario.win032',

    requires: [
        'Legalhelp.view.usuario.Win032ViewModel',
        'Legalhelp.view.usuario.Win032ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.field.TextArea',
        'Ext.field.File'
    ],

    controller: 'usuario.win032',
    viewModel: {
        type: 'usuario.win032'
    },
    id: 'Win032',
    scrollable: true,

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0321',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnFrmWin0321',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnFrmWin0321Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            html: '<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">Usuario</h3>'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Ingresa tus datos',
                    items: [
                        {
                            xtype: 'panel',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    name: 'primer_nombre',
                                    margin: '0 5 0 0',
                                    label: 'Primer nombre',
                                    labelAlign: 'bottom'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    name: 'segundo_nombre',
                                    label: 'Segundo nombre',
                                    labelAlign: 'bottom'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    name: 'primer_apellido',
                                    margin: '0 5 0 0',
                                    label: 'Primer apellido',
                                    labelAlign: 'bottom'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    name: 'segundo_apellido',
                                    label: 'Segundo apellido',
                                    labelAlign: 'bottom'
                                }
                            ]
                        },
                        {
                            xtype: 'emailfield',
                            name: 'email',
                            label: 'Correo',
                            labelAlign: 'bottom',
                            validators: 'email'
                        },
                        {
                            xtype: 'textfield',
                            name: 'telefono_principal',
                            label: 'Teléfono',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textareafield',
                            name: 'direccion',
                            label: 'Dirección',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'filefield',
                            name: 'xxx_archivo',
                            label: 'Imagen',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'txtWin0321',
                            name: 'imagen',
                            label: 'Field'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnFrmWin0322',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnFrmWin0322Tap'
            }
        }
    ]

});