/*
 * File: app/view/usuario/Win043.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.usuario.Win043', {
    extend: 'Ext.Panel',
    alias: 'widget.usuario.win043',

    requires: [
        'Legalhelp.view.usuario.Win043ViewModel',
        'Legalhelp.view.usuario.Win043ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Password'
    ],

    controller: 'usuario.win043',
    viewModel: {
        type: 'usuario.win043'
    },
    id: 'Win043',
    scrollable: true,

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0431',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnFrmWin0431',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnFrmWin0431Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            html: '<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">Cambiar contraseña</h3>'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Ingresa tu contraseña',
                    items: [
                        {
                            xtype: 'passwordfield',
                            name: 'clave',
                            label: 'Contraseña actual',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'passwordfield',
                            name: 'xxx_clave_nueva',
                            label: 'Contraseña nueva',
                            labelAlign: 'bottom',
                            revealable: true
                        },
                        {
                            xtype: 'passwordfield',
                            name: 'xxx_clave_repetida',
                            label: 'Repita la contraseña',
                            labelAlign: 'bottom',
                            revealable: true
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnFrmWin0432',
            docked: 'bottom',
            text: 'Cambiar',
            listeners: {
                tap: 'onBtnFrmWin0432Tap'
            }
        }
    ]

});