/*
 * File: app/view/usuario/Win043ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.usuario.Win043ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.usuario.win043',

    onBtnFrmWin0431Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnFrmWin0432Tap: function(button, e, eOpts) {
        var me = this;
        var formulario = Ext.getCmp('frmWin0431');

        formulario.submit({
            url    : '../servidor_legalhelp/usuario/cambiarcontrasena',
            method  : 'POST',
            params: {
                data: Ext.JSON.encode(formulario.getValues())
            },
            success: function (response, options)
            {
                //var responseData = Ext.JSON.decode(options.response.responseText);
                if(options.success)
                {
                    Ext.Msg.alert('Info', 'Se cambió la contraseña exitosamente');
                    var win = Ext.create('Legalhelp.view.menu.Win031', {fullscreen: true});
                    me.getView().destroy();
                }
                else
                Ext.Msg.alert('Error', 'No se ha podido cambiar la contraseña. Inténtalo más tarde.');
            },
            failure: function ()
            {
                var msg = 'No se ha podido cambiar la contraseña. Inténtalo más tarde.';
                Ext.Msg.alert('Error',msg);
            }
        });
    }

});