/*
 * File: app/view/tarjeta/Win033ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tarjeta.Win033ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tarjeta.win033',

    onBtnWin0331Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnFrmWin0333Tap: function(button, e, eOpts) {
        var forma = Ext.getCmp('frmWin0331');
        var id = forma.findField('tar_id').getValue();
        var store = forma.getStore();
        var selection = forma.getRecord();
        if(id !== 0 && id !== '0' && id !== '' && id !== null)
        {
            if (selection !== null && typeof(selection) !== 'undefined')
            {
                store.remove(selection);
                store.sync(
                {
                    success: function(batch, options)
                    {
                        store.commitChanges();
                    },
                    failure: function(batch, options)
                    {
                        store.rejectChanges();
                    }
                });
            }
        }
    },

    onBtnFrmWin0332Tap: function(button, e, eOpts) {
        var id = Ext.getCmp('frmWin0331').getValues().tar_id;
        Legalhelp.controller.Funciones.saveRecord('tarjeta.win033Store', 'frmWin0331');
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onWin033Added: function(component, container, index, eOpts) {

    }

});