/*
 * File: app/view/tarjeta/Win033.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tarjeta.Win033', {
    extend: 'Ext.Panel',
    alias: 'widget.tarjeta.win033',

    requires: [
        'Legalhelp.view.tarjeta.Win033ViewModel',
        'Legalhelp.view.tarjeta.Win033ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Number',
        'Ext.field.ComboBox',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.field.Password'
    ],

    controller: 'tarjeta.win033',
    viewModel: {
        type: 'tarjeta.win033'
    },
    id: 'Win033',
    scrollable: true,

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0331',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnFrmWin0331',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnWin0331Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0331',
                            html: '<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">Tarjeta</h3>'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    layout: 'vbox',
                    title: 'Ingresa tus datos',
                    items: [
                        {
                            xtype: 'textfield',
                            name: 'nombre_titular',
                            label: 'Nombre titular',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'numberfield',
                            name: 'numero_tarjeta',
                            label: 'Número tarjeta',
                            labelAlign: 'bottom',
                            maxLength: 16
                        },
                        {
                            xtype: 'combobox',
                            name: 'tta_id',
                            label: 'Tipo de tarjeta',
                            labelAlign: 'bottom',
                            displayField: 'nombre',
                            store: 'tipo_tarjeta.win015Store',
                            valueField: 'tta_id'
                        },
                        {
                            xtype: 'datefield',
                            name: 'xxx_fecha_vencimiento',
                            label: 'Fecha vencimiento',
                            labelAlign: 'bottom',
                            picker: {
                                xtype: 'datepicker',
                                title: 'Fecha vencimiento'
                            }
                        },
                        {
                            xtype: 'passwordfield',
                            name: 'xxx_cvc',
                            label: 'CVC',
                            labelAlign: 'bottom'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnFrmWin0332',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnFrmWin0332Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin033Added'
    }

});