/*
 * File: app/model/usuario/usuarioModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.model.usuario.usuarioModel', {
    extend: 'Ext.data.Model',
    alias: 'model.usuario.usuariomodel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],


    idProperty: 'usu_id',
    fields: [
        {
            type: 'int',
            name: 'usu_id',
            unique: true
        },
        {
            type: 'int',
            name: 'tid_id'
        },
        {
            type: 'string',
            name: 'primer_nombre'
        },
        {
            type: 'string',
            name: 'segundo_nombre'
        },
        {
            type: 'string',
            name: 'primer_apellido'
        },
        {
            type: 'string',
            name: 'segundo_apellido'
        },
        {
            type: 'string',
            name: 'telefono_principal'
        },
        {
            type: 'string',
            name: 'telefono_secundario'
        },
        {
            type: 'string',
            name: 'direccion'
        },
        {
            type: 'string',
            name: 'clave'
        },
        {
            type: 'string',
            name: 'email'
        },
        {
            type: 'string',
            name: 'identificacion'
        },
        {
            type: 'string',
            name: 'rol'
        },
        {
            type: 'string',
            name: 'xxx_rol'
        },
        {
            type: 'string',
            name: 'xxx_nombre_usuario'
        }
    ]

});