/*
 * File: app/view/tipo_especialidad/Win016ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tipo_especialidad.Win016ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tipo_especialidad.win016',

    deleteRecord: function() {
        Legalhelp.controller.Funciones.deleteRecord('lstWin0161');
    },

    editRecord: function() {
        var lista = Ext.getCmp('lstWin0161');
        var store = lista.getStore();
        var selection = lista._plugins[0].items[0]._record;
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.tipo_especialidad.Win022', 'frmWin0221', selection);
    },

    onBtnWin0161Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win012');
    },

    onBtnWin0162Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0163Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0164Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onBtnWin0165Tap: function(button, e, eOpts) {
        var rec = Ext.create('model.tipo_especialidad.tipoespecialidadmodel');
        rec.data.tes_id = '0';
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.tipo_especialidad.Win022', 'frmWin0221', rec);
    },

    onWin016Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0161').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
        Ext.getCmp('lstWin0161').getStore().load();
    }

});