/*
 * File: app/view/tipo_especialidad/Win016.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tipo_especialidad.Win016', {
    extend: 'Ext.Panel',
    alias: 'widget.tipo_especialidad.win016',

    requires: [
        'Legalhelp.view.tipo_especialidad.Win016ViewModel',
        'Legalhelp.view.tipo_especialidad.Win016ViewController',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.dataview.listswiper.ListSwiper',
        'Ext.dataview.pullrefresh.PullRefresh',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'tipo_especialidad.win016',
    viewModel: {
        type: 'tipo_especialidad.win016'
    },
    id: 'Win016',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'vbox',
            items: [
                {
                    xtype: 'list',
                    id: 'lstWin0161',
                    margin: '10 10 10 10',
                    itemTpl: [
                        '<div>{nombre}</div>'
                    ],
                    store: 'tipo_especialidad.win016Store',
                    plugins: [
                        {
                            right: [
                                {
                                    iconCls: 'x-fa fa-edit',
                                    commit: 'editRecord'
                                }
                            ],
                            left: [
                                {
                                    iconCls: 'x-fa fa-trash',
                                    commit: 'deleteRecord',
                                    ui: 'decline'
                                }
                            ],
                            widget: {
                                xtype: 'listswiperstepper'
                            },
                            type: 'listswiper'
                        },
                        {
                            type: 'pullrefresh'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0161',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0161Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0162',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0162Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0163',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0163Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0164',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0164Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0161'
                },
                {
                    xtype: 'button',
                    id: 'btnWin0165',
                    iconCls: 'x-fa fa-plus',
                    listeners: {
                        tap: 'onBtnWin0165Tap'
                    }
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin016Added'
    }

});