/*
 * File: app/view/tipo_especialidad/Win001ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.tipo_especialidad.Win001ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tipo_especialidad.win001',

    onDtvWin001Childtap: function(dataview, location, eOpts) {
        console.log(dataview);
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win004');
    },

    onBtnWin0011Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0012Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0013Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin001Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0011').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    }

});