/*
 * File: app/view/menu/Win004ViewController4.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.menu.Win004ViewController4', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.usuario.win009',

    onBtnWin0011Tap: function(button, e, eOpts) {
        var me = this;
        Ext.Ajax.request
        ({
            url: '../servidor_legalhelp/login/logout',
            method: 'GET',
            callback: function(opt, success, response)
            {
                if(success)
                {
                    var data = Ext.JSON.decode(response.responseText);
                    if(data.success)
                    {
                        Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.login.WinLogin');
                    }
                    else
                    Ext.Msg.alert('Error', 'Ha ocurrido un error al cerrar sesión');
                }
                else
                Ext.Msg.alert('Error', 'Error de conexión');
            }
        });
    },

    onBtnWin0012Tap: function(button, e, eOpts) {

    },

    onBtnWin0013Tap: function(button, e, eOpts) {

    },

    onWin0001Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0011').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    }

});