/*
 * File: app/view/menu/Win044.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.menu.Win044', {
    extend: 'Ext.Panel',
    alias: 'widget.menu.win044',

    requires: [
        'Legalhelp.view.menu.Win044ViewModel',
        'Legalhelp.view.menu.Win044ViewController',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Panel'
    ],

    controller: 'menu.win044',
    viewModel: {
        type: 'menu.win044'
    },
    id: 'Win044',
    layout: 'fit',

    items: [
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin32',
                    iconCls: 'x-fa fa-home',
                    listeners: {
                        tap: 'onBtnWin0031Tap'
                    }
                },
                {
                    xtype: 'panel',
                    html: '<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">Acerca de LegalHelp</h3>'
                }
            ]
        },
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'container',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'panel',
                            html: '<div><p>LegalHelp es una aplicación que le ayudará legalmente, asesorandolo paso a paso y guiándo sus pasos a soluciones de calidad</p><br><p>Estamos para asesorarle! </p></div>',
                            margin: '0 10 0 10'
                        }
                    ]
                }
            ]
        }
    ]

});