/*
 * File: app/view/menu/Win044ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.menu.Win044ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.menu.win044',

    onBtnWin0031Tap: function(button, e, eOpts) {
        if(ROL === 'CLI')
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.tipo_especialidad.Win001');
        else if(ROL === 'ADM')
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win012');
        else if(ROL === 'ABG')
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win028');
    }

});