/*
 * File: app/view/menu/Win031ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.menu.Win031ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.menu.win031',

    onBtnWin0315Tap: function(button, e, eOpts) {
        var rec = Ext.create('model.usuario.usuariomodel');
        var me = this;
        Ext.Ajax.request
        ({
            url: '../servidor_legalhelp/usuario/readusuario',
            method: 'POST',
            success: function (response) {
                var responseData = Ext.JSON.decode(response.responseText);
                if (!responseData.success)
                Ext.Msg.alert('Error', 'Ha ocurrido un error.');
                else
                {
                    var data = responseData.data;
                    rec.set(data);
                    if (data !== null)
                    Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.usuario.Win032', 'frmWin0321', rec);
                    else
                    Ext.Msg.alert('Error', 'Ha ocurrido un error.');
                }
            }
        });
    },

    onBtnWin0317Tap: function(button, e, eOpts) {
        var rec = Ext.create('model.usuario.usuariomodel');
        rec.data.usu_id = ID_USUARIO;
        rec.data.clave = '';
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.usuario.Win043', 'frmWin0431', rec);
        /*var rec = Ext.create('model.usuario.usuariomodel');
        var me = this;
        Ext.Ajax.request
        ({
        url: '../servidor_legalhelp/usuario/readusuario',
        method: 'POST',
        success: function (response) {
        var responseData = Ext.JSON.decode(response.responseText);
        if (!responseData.success)
        Ext.Msg.alert('Error', 'Ha ocurrido un error.');
        else
        {
        var data = responseData.data;
        rec.set(data);
        if (data !== null)
        Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.usuario.Win043', 'frmWin0431', rec);
        else
        Ext.Msg.alert('Error', 'Ha ocurrido un error.');
        }
        }
        });*/
    },

    onBtnWin0316Tap: function(button, e, eOpts) {
        var rec = Ext.create('model.tarjeta.tarjetamodel');
        var me = this;
        Ext.Ajax.request
        ({
            url: '../servidor_legalhelp/tarjeta/readtarjeta',
            method: 'POST',
            success: function (response) {
                var responseData = Ext.JSON.decode(response.responseText);
                if (!responseData.success)
                {
                    rec.data.tar_id = 0;
                    Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.tarjeta.Win033', 'frmWin0331', rec);
                }
                else
                {
                    var data = responseData.data;
                    if (data !== null)
                    {
                        rec.set(data);
                        Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.tarjeta.Win033', 'frmWin0331', rec);
                    }
                    else
                    {
                        rec.data.tar_id = 0;
                        Legalhelp.controller.Funciones.backWin(me, 'Legalhelp.view.tarjeta.Win033', 'frmWin0331', rec);
                    }
                }
            }
        });
    },

    onBtnWin0311Tap: function(button, e, eOpts) {
        if(ROL === 'CLI')
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.tipo_especialidad.Win001');
        else if(ROL === 'ADM')
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win012');
        else if(ROL === 'ABG')
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win028');
    },

    onBtnWin0312Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0314Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin031Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0311').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
        Ext.getCmp('imgWin0311').setSrc('../servidor_legalhelp/img/'+IMAGEN_USUARIO);
        Ext.getCmp('dsfWin0312').setHtml('<h1 style="margin:0;padding:0;color:#dcc13c">'+NOMBRE+'</h1>');
        if(ROL === 'CLI')
        {
            Ext.getCmp('btnWin0316').setHidden(false);
        }
        else
        {
            Ext.getCmp('btnWin0316').setHidden(true);
        }
    }

});