/*
 * File: app/view/menu/Win004.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.menu.Win004', {
    extend: 'Ext.Panel',
    alias: 'widget.menu.win004',

    requires: [
        'Legalhelp.view.menu.Win004ViewModel',
        'Legalhelp.view.menu.Win004ViewController',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'menu.win004',
    viewModel: {
        type: 'menu.win004'
    },
    id: 'Win004',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'container',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'dataview',
                            itemTpl: [
                                '<tpl for=".">',
                                '  <div class="thumb-wrap" id="{id}">',
                                '    <div class="thumb"><img src="{imagen}" height="42" title="{nombre}"/></div>',
                                '    <span>{nombre}</span>',
                                '  </div>',
                                '</tpl>'
                            ],
                            store: 'menu.win004Store',
                            listeners: {
                                childtap: 'onDtvWin0041Childtap'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0041',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0041Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0042',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0042Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0043',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin0043Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0044',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0044Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0041'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin004Added'
    }

});