/*
 * File: app/view/menu/Win031.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.menu.Win031', {
    extend: 'Ext.Panel',
    alias: 'widget.menu.win031',

    requires: [
        'Legalhelp.view.menu.Win031ViewModel',
        'Legalhelp.view.menu.Win031ViewController',
        'Ext.Img',
        'Ext.field.Display',
        'Ext.Button',
        'Ext.Toolbar',
        'Ext.menu.Menu'
    ],

    controller: 'menu.win031',
    viewModel: {
        type: 'menu.win031'
    },
    id: 'Win031',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'image',
                    height: 201,
                    id: 'imgWin0311',
                    width: 201
                },
                {
                    xtype: 'displayfield',
                    id: 'dsfWin0312'
                },
                {
                    xtype: 'button',
                    id: 'btnWin0315',
                    iconCls: 'x-fa fa-user',
                    text: 'Editar perfil',
                    listeners: {
                        tap: 'onBtnWin0315Tap'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnWin0317',
                    iconCls: 'x-fa fa-lock',
                    text: 'Cambiar contraseña',
                    listeners: {
                        tap: 'onBtnWin0317Tap'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnWin0316',
                    iconCls: 'x-fa fa-credit-card',
                    text: 'Datos tarjeta',
                    listeners: {
                        tap: 'onBtnWin0316Tap'
                    }
                },
                {
                    xtype: 'container',
                    layout: 'center'
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0311',
                    iconCls: 'x-fa fa-home',
                    listeners: {
                        tap: 'onBtnWin0311Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0312',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0312Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0314',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0314Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0311'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin031Added'
    }

});