/*
 * File: app/view/menu/Win028ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.menu.Win028ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.menu.win028',

    onDtvWin0281Childtap: function(dataview, location, eOpts) {
        switch(location.record.data.id)
        {
            case 1:
            case 2:
            case 3:
            Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.mensaje.Win029', 'lstWin0291', '',location.record.data.id, 'hdnWin0291');
            break;
            case 4://caso
            Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.caso.Win039');
            break;
            case 5://fuente
            Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.biblioteca.Win037');
            break;
        }
    },

    onBtnWin0281Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin0282Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0283Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin028Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0281').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    }

});