/*
 * File: app/view/caso/Win042.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.caso.Win042', {
    extend: 'Ext.Panel',
    alias: 'widget.caso.win042',

    requires: [
        'Legalhelp.view.caso.Win042ViewModel',
        'Legalhelp.view.caso.Win042ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.ComboBox',
        'Ext.field.TextArea',
        'Ext.field.Date',
        'Ext.picker.Date'
    ],

    controller: 'caso.win042',
    viewModel: {
        type: 'caso.win042'
    },
    id: 'Win042',
    scrollable: true,

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0421',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnFrmWin0421',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnFrmWin0421Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0421'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    scrollable: true,
                    layout: 'vbox',
                    title: 'Caso',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'cas_id',
                            label: 'Field'
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_abogado',
                            label: 'Abogado delegado',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_cliente',
                            label: 'Cliente',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'combobox',
                            name: 'esp_id',
                            label: 'Especialidad',
                            labelAlign: 'bottom',
                            editable: false,
                            displayField: 'nombre',
                            store: 'especialidad.especialidadCmbStore',
                            valueField: 'esp_id'
                        },
                        {
                            xtype: 'textfield',
                            name: 'nombre',
                            label: 'Nombre',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textareafield',
                            name: 'descripcion',
                            label: 'Descripción',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            name: 'numero_caso',
                            label: 'Número caso',
                            labelAlign: 'bottom'
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_estado',
                            label: 'Estado',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'fecha_inicio',
                            label: 'Fecha inicio',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'datefield',
                            name: 'fecha_cierre',
                            label: 'Fecha fin',
                            labelAlign: 'bottom',
                            picker: {
                                xtype: 'datepicker',
                                title: 'My Panel'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            id: 'btnFrmWin0422',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnFrmWin0422Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin042Added'
    }

});