/*
 * File: app/view/caso/Win030ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.caso.Win030ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.caso.win030',

    onBtnFrmWin0301Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.caso.Win020');
    },

    onWin030Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0301').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    },

    onBtnFrmWin0302Tap: function(button, e, eOpts) {
        /*Legalhelp.controller.Funciones.saveRecord('caso.win020Store', 'frmWin0301');
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.caso.Win020');*/
    }

});