/*
 * File: app/view/caso/Win020ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.caso.Win020ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.caso.win020',

    editRecord: function() {
        var lista = Ext.getCmp('lstWin0201');
        var store = lista.getStore();
        var selection = lista._plugins[0].items[0]._record;
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.caso.Win030', 'frmWin0301', selection);
    },

    onTxtWin0201Change: function(field, newValue, oldValue, eOpts) {
        var store = Ext.getCmp('lstWin0201').getStore();
        store.proxy.extraParams = {'filtro': newValue};
        store.load();
    },

    onBtnWin0201Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win012');
    },

    onBtnWin0202Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.logout(this);
    },

    onBtnWin00203Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win031');
    },

    onBtnWin0204Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.menu.Win044');
    },

    onWin020Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0201').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
        Ext.getCmp('lstWin0201').getStore().load();
    }

});