/*
 * File: app/view/caso/Win042ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.caso.Win042ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.caso.win042',

    onBtnFrmWin0421Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.mensaje.Win029');
    },

    onWin042Added: function(component, container, index, eOpts) {
        Ext.getCmp('dsfWin0421').setHtml('<h3 style="background-color:#c84911;margin:0;padding:0;color:#ffffff">'+NOMBRE+'</h3>');
    },

    onBtnFrmWin0422Tap: function(button, e, eOpts) {
        Legalhelp.controller.Funciones.saveRecord('caso.win042Store', 'frmWin0421');
        Legalhelp.controller.Funciones.backWin(this, 'Legalhelp.view.mensaje.Win029');
    }

});