/*
 * File: app/view/caso/Win020.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.caso.Win020', {
    extend: 'Ext.Panel',
    alias: 'widget.caso.win020',

    requires: [
        'Legalhelp.view.caso.Win020ViewModel',
        'Legalhelp.view.caso.Win020ViewController',
        'Ext.field.Text',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.dataview.listswiper.ListSwiper',
        'Ext.dataview.pullrefresh.PullRefresh',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.menu.Menu'
    ],

    controller: 'caso.win020',
    viewModel: {
        type: 'caso.win020'
    },
    id: 'Win020',
    layout: 'fit',

    items: [
        {
            xtype: 'container',
            layout: 'vbox',
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtWin0201',
                    margin: '5 10 5 10',
                    listeners: {
                        change: 'onTxtWin0201Change'
                    }
                },
                {
                    xtype: 'list',
                    id: 'lstWin0201',
                    margin: '10 10 10 10',
                    itemTpl: [
                        '<div>{numero_caso} - {nombre}<br>{descripcion}</div>'
                    ],
                    store: 'caso.win020Store',
                    plugins: [
                        {
                            right: [
                                {
                                    iconCls: 'x-fa fa-eye',
                                    commit: 'editRecord'
                                }
                            ],
                            widget: {
                                xtype: 'listswiperstepper'
                            },
                            type: 'listswiper'
                        },
                        {
                            type: 'pullrefresh'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    id: 'btnWin0201',
                    iconCls: 'x-fa fa-chevron-left',
                    listeners: {
                        tap: 'onBtnWin0201Tap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-bars',
                    menu: {
                        xtype: 'menu',
                        width: 200,
                        items: [
                            {
                                xtype: 'button',
                                id: 'btnWin0202',
                                iconCls: 'x-fa fa-sign-out',
                                text: 'Cerrar sesión',
                                listeners: {
                                    tap: 'onBtnWin0202Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0203',
                                iconCls: 'x-fa fa-user',
                                text: 'Mi cuenta',
                                listeners: {
                                    tap: 'onBtnWin00203Tap'
                                }
                            },
                            {
                                xtype: 'button',
                                id: 'btnWin0204',
                                iconCls: 'x-fa fa-info',
                                text: 'Acerca',
                                listeners: {
                                    tap: 'onBtnWin0204Tap'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'panel',
                    id: 'dsfWin0201'
                }
            ]
        }
    ],
    listeners: {
        added: 'onWin020Added'
    }

});