/*
 * File: app/view/caso/Win030.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.view.caso.Win030', {
    extend: 'Ext.Panel',
    alias: 'widget.caso.win030',

    requires: [
        'Legalhelp.view.caso.Win030ViewModel',
        'Legalhelp.view.caso.Win030ViewController',
        'Ext.form.Panel',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.TextArea'
    ],

    controller: 'caso.win030',
    viewModel: {
        type: 'caso.win030'
    },
    id: 'Win030',
    scrollable: true,

    items: [
        {
            xtype: 'formpanel',
            id: 'frmWin0301',
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnFrmWin0301',
                            iconCls: 'x-fa fa-chevron-left',
                            listeners: {
                                tap: 'onBtnFrmWin0301Tap'
                            }
                        },
                        {
                            xtype: 'panel',
                            id: 'dsfWin0301'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    scrollable: true,
                    layout: 'vbox',
                    title: 'Caso',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'cas_id',
                            label: 'Field'
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_abogado',
                            label: 'Abogado delegado',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_cliente',
                            label: 'Cliente',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_especialidad',
                            label: 'Especialidad',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'nombre',
                            label: 'Nombre',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textareafield',
                            name: 'descripcion',
                            label: 'Descripción',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'numero_caso',
                            label: 'Número caso',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'xxx_estado',
                            label: 'Estado',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'fecha_inicio',
                            label: 'Fecha inicio',
                            labelAlign: 'bottom',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            name: 'fecha_cierre',
                            label: 'Fecha fin',
                            labelAlign: 'bottom',
                            readOnly: true
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            hidden: true,
            id: 'btnFrmWin0302',
            docked: 'bottom',
            text: 'Grabar',
            listeners: {
                tap: 'onBtnFrmWin0302Tap'
            }
        }
    ],
    listeners: {
        added: 'onWin030Added'
    }

});