/*
 * File: app/store/biblioteca/win034Store1.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Legalhelp.store.biblioteca.win034Store1', {
    extend: 'Ext.data.Store',

    requires: [
        'Legalhelp.model.biblioteca.bibliotecaModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'biblioteca.win034Store1',
            autoSync: true,
            model: 'Legalhelp.model.biblioteca.bibliotecaModel',
            proxy: {
                type: 'ajax',
                api: {
                    read: '../servidor_legalhelp/biblioteca/getbiblioteca',
                    create: '../servidor_legalhelp/biblioteca/savebiblioteca',
                    update: '../servidor_legalhelp/biblioteca/savebiblioteca',
                    destroy: '../servidor_legalhelp/biblioteca/deletebiblioteca'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data',
                    metaProperty: 'newId'
                },
                writer: {
                    type: 'json',
                    encode: true,
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});